[build]
builder = "nixpacks"
buildCommand = "pip install -r src/backend/requirements.txt"

[deploy]
startCommand = "cd src/backend && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
