[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

# Optional (you can omit this since railway.toml already sets startCommand)
[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
